### ISSUE TITLE
Coisas para fazer

### ISSUE THREAD

**Issue by BeahIF** [SraWesley/BookIsLife#1]
Tem que fazer a página de cadastro, vejam seus emails onde mandei umas coisas para ajudar. Ana e Laura decidam quem vai fazer e na quarta a gente ve com o Márcio o que mais podemos fazer, pq agora eu não tenho ideia.

**Comment by BeahIF** [comment]
Alguma evolução?

**Comment by SraWesley** [comment]
Eu te amo <3

**Comment by lauratgomes** [comment]
Ainda não, mas provavelmente no fim de semana eu suba alguma coisa

**Comment by SraWesley** [comment]
Eu vou tentar mas sou um desastre então.

**Comment by lauratgomes** [comment]
Finalmente consegui abrir meu eclipse. Começo o formulário hoje.

**Comment by SraWesley** [comment]
Estou trabalhando nos códigos que a Bea havia feito, tem algum problema com o delete que ainda não consegui resolver. Fiz poucas modificações por enquanto, apenas retirei os "LSLS" e os "OK" que ficavam apararecendo e corrigi um erro no delete da bea, a pasta estava "Lilmes" e eu arrumei. Tentando ver qual foi o erro do delete, mando mensagem aqui se achar algo.

**Comment by lauratgomes** [comment]
Gurias eu tava vendo e tipo, quando a pessoa loga não pode ir direto para uma página de editar o perfil. Acho que poderíamos ver se dá pra fazer na mesma página, entendem? E tem mais uma coisinhas, mas é mais coisa de estética e paranoia minha. Fora isso nada demais. Beijinhos de luz no <3
