### ISSUE TITLE
Coisas que o Márcio pediu

### ISSUE THREAD

**Issue by BeahIF** [SraWesley/BookIsLife#3]
Para próxima quarta 23/09
-> Persistir (salvar) (ou seja, o nosso faz isso, mas ainda tem coisas para arrumar, a Laura vai levar para o Márcio nos dar um help) e também tem coisas para terminar
 -> Listar (matéria da aula de hoje) (se meu pc funfar eu faço isso) 
-> Outra interação (excluir, editar, ...)

**Comment by lauratgomes** [comment]
Consegui fazer o listar os usuários em outro link, precisamos ainda cadastrar e listar os livros

**Comment by lauratgomes** [comment]
O cadastro dos livros é com a Ana, posso fazer a parte da HTML. O excluir, o editar vou falar com ele. Pq não entendi direito. Tipo excluir/editar o que?

**Comment by lauratgomes** [comment]
O projeto que subi hoje tem problemas, mas vou falar com o Márcio na sexta e tentar arrumar
