### ISSUE TITLE
Até o dia 25/11

### ISSUE THREAD

**Issue by lauratgomes** [SraWesley/BookIsLife#6]
Qualidade
- Externa
  - Layout
  - Navegabilidade
  - Confiável
  - Tratamento de erros
  - Corretude
- Interna
  - Reaproveitamento de código (métodos, superclasses e subclasses, ...)
  - Formato (identado, nomes legíveis, ...)
  - Oraganizado (pacotes, atributos de acordo com a classe, ...)
  - Orientação a Objetos (se são usadas classes e métodos, ...)

Apresentação
- Explicação (deixar bem claro a proposta, além de falar das dificuldades (com revezamento))

**Comment by lauratgomes** [comment]
Quando puderes me dá a tua opinião sobre o que achas que falta ou se tá bom....

**Comment by BeahIF** [comment]
Eu acho que tá tudo ok.
