### ISSUE TITLE
Projetos #UmaCoisaDeCadaVez

### ISSUE THREAD

**Issue by lauratgomes** [SraWesley/BookIsLife#7]
Bom, agora que conseguimos andar um pouco com o projeto e a medida que estamos terminando o que já havíamos planejado. Temos que pensar no que falta e dividirmos essas funções. 
Enfim, o design é comigo. Beah se quiseres ajudar será bem-vinda kk
Java e HTML podemos fazer juntas pelo Skype, na sala ou no atendimento e... Eu sei
# UmaCoisaDeCadaVez

**Comment by lauratgomes** [comment]
Seria:
- Tratar os erros;
- Add livros na biblioteca pessoal;
- Resenhas (método post --> Mural);
- Avaliação dos livros e/ou resenhas.

Né?

**Comment by BeahIF** [comment]
Estou tratando os erros, a biblioteca pessoal está funcionando e o Mural tu vai fazer e eu irei ajudar. A avaliação não vai rolar.

**Comment by lauratgomes** [comment]
Ok. Até amanhã devo estar com quase todo o CSS pronto. E no atendimento a gente faz o Mural (com todas as resenhas de todos os usuários) e o "mural pessoal" com todas as resenhas do usuário.

**Comment by lauratgomes** [comment]
- Tratar erros - Ok
- Add livros nas biblioteca pessoal - Ok
- Resenhas (método post --> Mural) - Ok
- Avaliação dos livros e/ou resenhas - faltou tempo! :/

**Comment by lauratgomes** [comment]
Fizemos tudo o que tínhamos planejado, exceto a avaliação dos livros e/ou resenhas, por falta de tempo

**Comment by lauratgomes** [comment]
Mas vai dar tudo certo
